/*
 * AdmitManageHosView.java
 *
 * Created on __DATE__, __TIME__
 */

package win.wangshengan.hotelhousing.view;

import java.awt.event.ActionEvent;
import java.sql.Date;
import java.util.List;
import java.util.Vector;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import win.wangshengan.hotelhousing.business.CountsBuss;
import win.wangshengan.hotelhousing.business.HistoryBuss;
import win.wangshengan.hotelhousing.business.RoomBuss;
import win.wangshengan.hotelhousing.business.RoomCheckInBuss;
import win.wangshengan.hotelhousing.business.TurnoverBuss;
import win.wangshengan.hotelhousing.business.impl.CountsBussImpl;
import win.wangshengan.hotelhousing.business.impl.HistoryBussImpl;
import win.wangshengan.hotelhousing.business.impl.RoomBussImpl;
import win.wangshengan.hotelhousing.business.impl.RoomCheckInBussImpl;
import win.wangshengan.hotelhousing.business.impl.TurnoverBussImpl;
import win.wangshengan.hotelhousing.entity.Counts;
import win.wangshengan.hotelhousing.entity.History;
import win.wangshengan.hotelhousing.entity.RoomCheckIn;
import win.wangshengan.hotelhousing.entity.Rooms;
import win.wangshengan.hotelhousing.entity.Turnover;
import win.wangshengan.hotelhousing.util.Format;

/**
 *
 * @author  __USER__
 */
public class AdmitManageHosView extends javax.swing.JPanel {

	int admin = -1;
	RoomCheckInBuss roomCheckInBuss = new RoomCheckInBussImpl();
	RoomBuss roomBuss = new RoomBussImpl();
	CountsBuss countsBuss = new CountsBussImpl();
	HistoryBuss historyBuss = new HistoryBussImpl();
	TurnoverBuss turnoverBuss = new TurnoverBussImpl();

	public AdmitManageHosView() {

	}

	/** Creates new form AdmitManageHosView */
	public AdmitManageHosView(int admin) {
		initComponents();
		jtfadd.setVisible(false);
		jlbadd.setVisible(false);
		this.admin = admin;
		this.setSize(638, 624);
		this.setOpaque(false);
		jPanel1.setOpaque(false);
		jPanel2.setOpaque(false);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jtfname = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jtfid = new javax.swing.JTextField();
		jtfroomno = new javax.swing.JTextField();
		jLabel9 = new javax.swing.JLabel();
		jtfbegin = new javax.swing.JTextField();
		jLabel10 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jtfpaid = new javax.swing.JTextField();
		jLabel8 = new javax.swing.JLabel();
		jtfvalue = new javax.swing.JTextField();
		jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		jLabel11 = new javax.swing.JLabel();
		jlbmoney = new javax.swing.JLabel();
		lbalert = new javax.swing.JLabel();
		cbstate = new javax.swing.JComboBox();
		jlbadd = new javax.swing.JLabel();
		jtfadd = new javax.swing.JTextField();
		jtfend = new javax.swing.JTextField();
		jPanel2 = new javax.swing.JPanel();
		jLabel6 = new javax.swing.JLabel();
		jtfuname = new javax.swing.JTextField();
		jLabel7 = new javax.swing.JLabel();
		jLabel12 = new javax.swing.JLabel();
		jtfrno = new javax.swing.JTextField();
		jtfuid = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		jlbInfo = new javax.swing.JTable();
		jLabel14 = new javax.swing.JLabel();

		jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(
				javax.swing.BorderFactory.createTitledBorder(""),
				"\u623f\u95f4\u4fe1\u606f",
				javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
				javax.swing.border.TitledBorder.DEFAULT_POSITION,
				new java.awt.Font("华文新魏", 0, 14), new java.awt.Color(255, 255,
						255)));
		jPanel1.setForeground(new java.awt.Color(204, 0, 0));

		jLabel1.setFont(new java.awt.Font("华文新魏", 0, 14));
		jLabel1.setForeground(new java.awt.Color(255, 255, 255));
		jLabel1.setText("\u5ba2\u6237\u59d3\u540d");

		jtfname.setEditable(false);

		jLabel2.setFont(new java.awt.Font("华文新魏", 0, 14));
		jLabel2.setForeground(new java.awt.Color(255, 255, 255));
		jLabel2.setText("\u8eab\u4efd\u8bc1\u53f7");

		jLabel3.setFont(new java.awt.Font("华文新魏", 0, 14));
		jLabel3.setForeground(new java.awt.Color(255, 255, 255));
		jLabel3.setText("\u623f\u95f4\u72b6\u6001");

		jLabel4.setFont(new java.awt.Font("华文新魏", 0, 14));
		jLabel4.setForeground(new java.awt.Color(255, 255, 255));
		jLabel4.setText("\u623f\u95f4\u7f16\u53f7");

		jtfid.setEditable(false);

		jtfroomno.setEditable(false);

		jLabel9.setFont(new java.awt.Font("华文新魏", 0, 14));
		jLabel9.setForeground(new java.awt.Color(255, 255, 255));
		jLabel9.setText("\u5165\u4f4f\u65e5\u671f");

		jtfbegin.setEditable(false);

		jLabel10.setFont(new java.awt.Font("华文新魏", 0, 14));
		jLabel10.setForeground(new java.awt.Color(255, 255, 255));
		jLabel10.setText("\u9000\u623f\u65e5\u671f");

		jLabel5.setFont(new java.awt.Font("华文新魏", 0, 14));
		jLabel5.setForeground(new java.awt.Color(255, 255, 255));
		jLabel5.setText("\u5df2\u4ed8\u91d1\u989d");

		jtfpaid.setEditable(false);

		jLabel8.setFont(new java.awt.Font("华文新魏", 0, 14));
		jLabel8.setForeground(new java.awt.Color(255, 255, 255));
		jLabel8.setText("\u4f4f\u623f\u6d88\u8d39");

		jButton2.setFont(new java.awt.Font("华文新魏", 1, 14));
		jButton2.setForeground(new java.awt.Color(0, 0, 255));
		jButton2.setText("\u4fee\u6539\u623f\u95f4");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jButton3.setFont(new java.awt.Font("华文新魏", 1, 14));
		jButton3.setForeground(new java.awt.Color(0, 0, 204));
		jButton3.setText("\u9000 \u623f");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});

		jLabel11.setFont(new java.awt.Font("华文新魏", 1, 14));
		jLabel11.setForeground(new java.awt.Color(255, 255, 255));
		jLabel11.setText("\u4f4f\u623f\u9000\u6b3e\uffe5");

		jlbmoney.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18));
		jlbmoney.setForeground(new java.awt.Color(255, 0, 0));
		jlbmoney.setText(" ");

		lbalert.setFont(new java.awt.Font("华文新魏", 0, 14));
		lbalert.setForeground(new java.awt.Color(255, 0, 0));
		lbalert.setText(" ");

		cbstate.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"预", "满" }));

		jlbadd.setFont(new java.awt.Font("华文新魏", 0, 14));
		jlbadd.setForeground(new java.awt.Color(255, 255, 255));
		jlbadd.setText("\u52a0\u65f6\u623f\u4ef7");

		jtfend.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jtfendMouseClicked(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addComponent(
																				jlbadd)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jtfadd))
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel1)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jtfname,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				67,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel4)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jtfroomno,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				67,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGap(43,
																				43,
																				43)
																		.addComponent(
																				jButton2)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																				37,
																				Short.MAX_VALUE)
																		.addComponent(
																				jButton3,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				87,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(32,
																				32,
																				32))
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																jPanel1Layout
																		.createSequentialGroup()
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING)
																						.addComponent(
																								lbalert,
																								javax.swing.GroupLayout.Alignment.LEADING,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								280,
																								Short.MAX_VALUE)
																						.addGroup(
																								jPanel1Layout
																										.createSequentialGroup()
																										.addGroup(
																												jPanel1Layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING)
																														.addComponent(
																																jLabel2)
																														.addComponent(
																																jLabel3))
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																										.addGroup(
																												jPanel1Layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING,
																																false)
																														.addComponent(
																																cbstate,
																																0,
																																javax.swing.GroupLayout.DEFAULT_SIZE,
																																Short.MAX_VALUE)
																														.addComponent(
																																jtfid,
																																javax.swing.GroupLayout.DEFAULT_SIZE,
																																70,
																																Short.MAX_VALUE))
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																										.addGroup(
																												jPanel1Layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING)
																														.addComponent(
																																jLabel5)
																														.addComponent(
																																jLabel8))
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																										.addGroup(
																												jPanel1Layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.TRAILING)
																														.addComponent(
																																jtfvalue,
																																javax.swing.GroupLayout.DEFAULT_SIZE,
																																62,
																																Short.MAX_VALUE)
																														.addComponent(
																																jtfpaid,
																																javax.swing.GroupLayout.Alignment.LEADING,
																																javax.swing.GroupLayout.DEFAULT_SIZE,
																																62,
																																Short.MAX_VALUE))))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																				7,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGap(19,
																				19,
																				19)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING)
																						.addComponent(
																								jLabel9)
																						.addComponent(
																								jLabel10)))
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jLabel11)))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(
																jtfbegin,
																javax.swing.GroupLayout.Alignment.LEADING,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																89,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jtfend,
																javax.swing.GroupLayout.Alignment.LEADING,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																89,
																Short.MAX_VALUE)
														.addComponent(
																jlbmoney,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																89,
																Short.MAX_VALUE))
										.addContainerGap()));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel1)
														.addComponent(
																jtfname,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jtfbegin,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel9)
														.addComponent(jLabel2)
														.addComponent(
																jtfid,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel5)
														.addComponent(
																jtfpaid,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(20, 20, 20)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel4)
														.addComponent(
																jtfroomno,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel10)
														.addComponent(jLabel3)
														.addComponent(
																cbstate,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jtfend,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel8)
														.addComponent(
																jtfvalue,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jlbadd)
																						.addComponent(
																								jtfadd,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								lbalert))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jButton2)
																						.addComponent(
																								jButton3)))
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGap(31,
																				31,
																				31)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jLabel11)
																						.addComponent(
																								jlbmoney))))
										.addContainerGap()));

		jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(
				javax.swing.BorderFactory.createLineBorder(new java.awt.Color(
						255, 255, 255)), "\u623f\u95f4\u67e5\u8be2",
				javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
				javax.swing.border.TitledBorder.DEFAULT_POSITION,
				new java.awt.Font("华文新魏", 0, 14), new java.awt.Color(255, 255,
						255)));
		jPanel2.setForeground(new java.awt.Color(255, 255, 255));

		jLabel6.setFont(new java.awt.Font("华文新魏", 0, 14));
		jLabel6.setForeground(new java.awt.Color(255, 255, 255));
		jLabel6.setText("\u5ba2\u6237\u59d3\u540d");

		jLabel7.setFont(new java.awt.Font("华文新魏", 0, 14));
		jLabel7.setForeground(new java.awt.Color(255, 255, 255));
		jLabel7.setText("\u8eab\u4efd\u8bc1\u53f7");

		jLabel12.setFont(new java.awt.Font("华文新魏", 0, 14));
		jLabel12.setForeground(new java.awt.Color(255, 255, 255));
		jLabel12.setText("\u623f\u95f4\u7f16\u53f7");

		jButton1.setFont(new java.awt.Font("华文新魏", 1, 14));
		jButton1.setForeground(new java.awt.Color(0, 0, 204));
		jButton1.setIcon(new javax.swing.ImageIcon(
				"D:\\MyeclipseWork\\hotelhousing1\\images\\查询.png")); // NOI18N
		jButton1.setText("\u67e5\u8be2");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
				jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout
				.setHorizontalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel2Layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(jLabel6)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jtfuname,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												78,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(jLabel7)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jtfuid,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												87,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(jLabel12)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jtfrno,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												75,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												62, Short.MAX_VALUE)
										.addComponent(
												jButton1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												88,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap()));
		jPanel2Layout
				.setVerticalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel2Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel6)
														.addComponent(jLabel7)
														.addComponent(
																jtfrno,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel12)
														.addComponent(
																jtfuid,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jtfuname,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jButton1))
										.addGap(27, 27, 27)));

		jlbInfo.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] {

				}, new String[] { "客户姓名", "身份证号", "房间编号", "房间型号", "房间状态",
						"房间价格", "入房日期", "退房日期" }) {
			boolean[] canEdit = new boolean[] { false, false, false, false,
					false, false, false, false };

			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		});
		jlbInfo.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jlbInfoMouseClicked(evt);
			}
		});
		jScrollPane1.setViewportView(jlbInfo);

		jLabel14.setFont(new java.awt.Font("华文新魏", 1, 36));
		jLabel14.setForeground(new java.awt.Color(255, 255, 255));
		jLabel14.setText("\u623f\u95f4\u7ba1\u7406");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addContainerGap()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						jPanel2,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						Short.MAX_VALUE)
																				.addComponent(
																						jScrollPane1,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						631,
																						Short.MAX_VALUE)
																				.addComponent(
																						jPanel1,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						Short.MAX_VALUE)))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(229,
																		229,
																		229)
																.addComponent(
																		jLabel14,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		159,
																		javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addContainerGap()));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jLabel14)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jPanel2,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										91,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jScrollPane1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										238,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jPanel1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)));
	}// </editor-fold>
	//GEN-END:initComponents

	//清空界面
	private void clear() {
		lbalert.setText("");
		jtfuname.setText("");
		jtfuid.setText("");
		jtfrno.setText("");
		jtfname.setText("");
		jtfid.setText("");
		jtfbegin.setText("");
		jtfend.setText("");
		jtfpaid.setText("");
		jtfroomno.setText("");
		jtfvalue.setText("");
		jtfadd.setText("");
		jlbmoney.setText(" ");
		DefaultTableModel dtm = (DefaultTableModel) jlbInfo.getModel();
		dtm.setRowCount(0);
	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		lbalert.setText("");
		String roomno = jtfroomno.getText();
		if ("".equals(roomno)) {
			lbalert.setText("警告：请选择所要修改的房间！");
			return;
		}
		int rno = Integer.parseInt(roomno);
		String userid = jtfid.getText();
		String rstate = cbstate.getSelectedItem() + "";
		String rvalue = jtfvalue.getText();
		String addValue = jtfadd.getText();
		Date endTime = Date.valueOf(jtfend.getText());
		int roomstate = 0;
		if ("预".equals(rstate)) {
			roomstate = 1;
		} else if ("满".equals(rstate)) {
			roomstate = 2;
		}
		boolean updaRstate = roomBuss.updateRoom(new Rooms(rno, "", rstate, "",
				-1));
		boolean rci = roomCheckInBuss.updateRoomCheckIn(new RoomCheckIn(-1, "",
				userid, new Date(1), endTime, roomstate, -1));
		boolean countsBus = true;
		if (!"".equals(addValue)) {
			Counts counts = countsBuss.getCountById(userid);
			int totalValue = counts.getPaid() + Integer.parseInt(addValue);
			countsBus = countsBuss.updateCount(new Counts("", userid,
					totalValue, -1, -1));
		}
		if (updaRstate && rci && countsBus) {
			JOptionPane.showMessageDialog(null, "修改房间信息成功！");
		} else {
			lbalert.setText("提示：修改房间失败！");
		}
	}

	//退房时的操作
	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		lbalert.setText("");
		String roomno = jtfroomno.getText();
		if ("".equals(roomno)) {
			lbalert.setText("警告：请选择所要退的房间！");
			return;
		}
		int rno = Integer.parseInt(roomno);
		String uname = jtfname.getText();
		String uid = jtfid.getText();
		String beginTime = jtfbegin.getText();
		String endTime = jtfend.getText();
		int value = Integer.parseInt(jtfvalue.getText());
		//修改房间状态，把房间状态重新设置为空
		boolean updRoom = roomBuss.updateRoom(new Rooms(rno, "", "空", "", -1));
		String rstate = cbstate.getSelectedItem() + "";
		boolean isAddHistory = true;
		boolean isTurnover = true;
		if ("满".equals(rstate)) {
			isAddHistory = historyBuss.addHistory(new History(rno, uname, uid,
					Date.valueOf(beginTime), Date.valueOf(endTime), new Date(
							new java.util.Date().getTime()), admin));
			//计算今日营业额
			Turnover turnover = turnoverBuss.getTurnover(new Turnover(endTime,
					-1));
			if (turnover == null) {
				isTurnover = turnoverBuss.addTurnover(new Turnover(endTime,
						value));

			} else {
				int value1 = 0;
				value1 = turnover.getTotalMoney();
				isTurnover = turnoverBuss.updateTurnover(new Turnover(endTime,
						value + value1));
			}
		}
		boolean delRoomCheckIn = roomCheckInBuss.delRoomCheckIn(uid);
		boolean delCounts = countsBuss.delCount(uid);
		if (updRoom && isAddHistory && isTurnover && delRoomCheckIn
				&& delCounts) {
			JOptionPane.showMessageDialog(null, "退房成功！");
			clear();
		} else {
			lbalert.setText("警告：退房失败！");
		}
	}

	//点击退房文本框，显示续房加钱文本框
	private void jtfendMouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		jtfadd.setVisible(true);
		jlbadd.setVisible(true);
	}

	//点击table表格后，填充住房信息
	private void jlbInfoMouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		lbalert.setText("");
		int rowNum = jlbInfo.getSelectedRow();
		String uid = jlbInfo.getValueAt(rowNum, 1) + "";
		Counts counts = countsBuss.getCountById(uid);
		int paid = counts.getPaid();
		int value = Integer.parseInt(jlbInfo.getValueAt(rowNum, 5) + "");
		jtfname.setText(jlbInfo.getValueAt(rowNum, 0) + "");
		jtfid.setText(uid);
		jtfpaid.setText(counts.getPaid() + "");
		jtfroomno.setText(jlbInfo.getValueAt(rowNum, 2) + "");
		String rstate = jlbInfo.getValueAt(rowNum, 4) + "";
		cbstate.setSelectedItem(rstate);
		jtfvalue.setText(value + "");
		jtfbegin.setText(jlbInfo.getValueAt(rowNum, 6) + "");
		jtfend.setText(jlbInfo.getValueAt(rowNum, 7) + "");
		jlbmoney.setText((paid - value) + "");
	}

	//查询按钮操作
	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		lbalert.setText("");
		String uname = jtfuname.getText();
		String uid = jtfuid.getText();
		String rno = jtfrno.getText();
		//查询条件不能全为空
		if ("".equals(uname) && "".equals(uid) && "".equals(rno)) {
			lbalert.setText("警告：请输入要查询的信息！");
			return;
		}
		int roomno = -1;
		//当rno文本框不为空时，判断其是否输入全数字格式
		if (!"".equals(rno)) {
			boolean flag = Format.isStringToNumber(rno);
			if (flag) {
				roomno = Integer.parseInt(rno);
			} else {
				lbalert.setText("警告：房间编号只能输入数字！");
				return;
			}
		}
		//通过三个条分别获取房间表、房间结算表以及房间预住表信息
		RoomCheckIn roomCheckIn = roomCheckInBuss
				.getselectAllRoomCheckInByCondition(new RoomCheckIn(roomno,
						uname, uid, new Date(1), new Date(1), -1, -1));
		if (roomCheckIn == null) {
			JOptionPane.showMessageDialog(null, "对不起，该客户没有住房！");
			return;
		}
		Rooms room = roomBuss.getRoomsById(roomCheckIn.getRno());
		Counts counts = countsBuss.getCountById(roomCheckIn.getUserid());
		//通过时间计算其房间价格
		Date beginTime = roomCheckIn.getBeginTime();
		Date endTime = roomCheckIn.getEndTime();
		Long begin = beginTime.getTime() + 43200000;//中午12点后开始算时间
		Long end = endTime.getTime() + 43200000;
		Long time = end - begin;
		int value = (int) (time * room.getRvalue() / 86400000);
		//填充表格
		DefaultTableModel dtm = (DefaultTableModel) jlbInfo.getModel();
		dtm.setRowCount(0);
		Vector v = new Vector();
		v.add(roomCheckIn.getUname());
		v.add(roomCheckIn.getUserid());
		v.add(roomCheckIn.getRno());
		v.add(room.getRtype());
		v.add(room.getRstate());
		v.add(value);
		v.add(beginTime);
		v.add(endTime);
		dtm.addRow(v);
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JComboBox cbstate;
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel14;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jlbInfo;
	private javax.swing.JLabel jlbadd;
	private javax.swing.JLabel jlbmoney;
	private javax.swing.JTextField jtfadd;
	private javax.swing.JTextField jtfbegin;
	private javax.swing.JTextField jtfend;
	private javax.swing.JTextField jtfid;
	private javax.swing.JTextField jtfname;
	private javax.swing.JTextField jtfpaid;
	private javax.swing.JTextField jtfrno;
	private javax.swing.JTextField jtfroomno;
	private javax.swing.JTextField jtfuid;
	private javax.swing.JTextField jtfuname;
	private javax.swing.JTextField jtfvalue;
	private javax.swing.JLabel lbalert;
	// End of variables declaration//GEN-END:variables

}