/*
 * AdmitUpdaInfoView.java
 *
 * Created on __DATE__, __TIME__
 */

package win.wangshengan.hotelhousing.view;

import javax.swing.JOptionPane;

import win.wangshengan.hotelhousing.business.AdmitBuss;
import win.wangshengan.hotelhousing.business.impl.AdmitBussImpl;
import win.wangshengan.hotelhousing.entity.Admit;

/**
 *
 * @author  __USER__
 */
public class AdmitUpdaInfoView extends javax.swing.JPanel {
	int id;
	AdmitBuss admitBuss = new AdmitBussImpl();

	public AdmitUpdaInfoView() {

	}

	/** Creates new form AdmitUpdaInfoView */
	public AdmitUpdaInfoView(int id) {
		this.id = id;
		initComponents();
		initiaInfo(id);
		this.setSize(638, 624);
		this.setOpaque(false);
	}

	/**
	 * 初始化界面
	 * @param id
	 */
	private void initiaInfo(int id) {
		jtfaid.setText(id + "");
		jtfpsw.setText("");
		jtfpsws.setText("");
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jtfaid = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jtfpsw = new javax.swing.JPasswordField();
		jtfpsws = new javax.swing.JPasswordField();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		lbinfo = new javax.swing.JLabel();

		jLabel1.setFont(new java.awt.Font("华文新魏", 1, 36));
		jLabel1.setForeground(new java.awt.Color(255, 255, 255));
		jLabel1.setText("\u4e2a\u4eba\u4fe1\u606f\u4fee\u6539");

		jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14));
		jLabel2.setForeground(new java.awt.Color(255, 255, 255));
		jLabel2.setText("       ID");

		jtfaid.setEditable(false);

		jLabel3.setFont(new java.awt.Font("华文新魏", 0, 14));
		jLabel3.setForeground(new java.awt.Color(255, 255, 255));
		jLabel3.setText("     \u5bc6\u7801");

		jLabel4.setFont(new java.awt.Font("华文新魏", 0, 14));
		jLabel4.setForeground(new java.awt.Color(255, 255, 255));
		jLabel4.setText("\u786e\u5b9a\u5bc6\u7801");

		jButton1.setFont(new java.awt.Font("华文新魏", 0, 14));
		jButton1.setForeground(new java.awt.Color(0, 0, 204));
		jButton1.setIcon(new javax.swing.ImageIcon(
				"D:\\MyeclipseWork\\hotelhousing1\\images\\提交.png")); // NOI18N
		jButton1.setText("\u63d0\u4ea4");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton2.setFont(new java.awt.Font("华文新魏", 0, 14));
		jButton2.setForeground(new java.awt.Color(0, 0, 204));
		jButton2.setIcon(new javax.swing.ImageIcon(
				"D:\\MyeclipseWork\\hotelhousing1\\images\\放弃.png")); // NOI18N
		jButton2.setText("\u653e\u5f03");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		lbinfo.setForeground(new java.awt.Color(255, 0, 0));
		lbinfo.setText("  ");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGap(174,
																		174,
																		174)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING)
																												.addComponent(
																														jLabel2)
																												.addComponent(
																														jLabel3)
																												.addComponent(
																														jLabel4))
																								.addGap(46,
																										46,
																										46)
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING,
																												false)
																												.addComponent(
																														jtfpsw,
																														0,
																														0,
																														Short.MAX_VALUE)
																												.addComponent(
																														jtfaid,
																														javax.swing.GroupLayout.DEFAULT_SIZE,
																														124,
																														Short.MAX_VALUE)
																												.addComponent(
																														jtfpsws,
																														javax.swing.GroupLayout.PREFERRED_SIZE,
																														159,
																														javax.swing.GroupLayout.PREFERRED_SIZE)))
																				.addGroup(
																						layout.createSequentialGroup()
																								.addGap(20,
																										20,
																										20)
																								.addComponent(
																										jButton1,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										82,
																										javax.swing.GroupLayout.PREFERRED_SIZE)
																								.addGap(39,
																										39,
																										39)
																								.addComponent(
																										jButton2,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										84,
																										javax.swing.GroupLayout.PREFERRED_SIZE))
																				.addGroup(
																						javax.swing.GroupLayout.Alignment.TRAILING,
																						layout.createSequentialGroup()
																								.addComponent(
																										lbinfo,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										178,
																										javax.swing.GroupLayout.PREFERRED_SIZE)
																								.addGap(50,
																										50,
																										50))))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(189,
																		189,
																		189)
																.addComponent(
																		jLabel1)))
								.addContainerGap(203, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(36, 36, 36)
								.addComponent(jLabel1)
								.addGap(66, 66, 66)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel2)
												.addComponent(
														jtfaid,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(29, 29, 29)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel3)
												.addComponent(
														jtfpsw,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(34, 34, 34)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel4)
												.addComponent(
														jtfpsws,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(lbinfo)
								.addGap(34, 34, 34)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jButton1)
												.addComponent(jButton2))
								.addContainerGap(272, Short.MAX_VALUE)));
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		initiaInfo(id);
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		String psw = jtfpsw.getText();
		String psws = jtfpsws.getText();
		if ("".equals(psw) || "".equals(psws)) {
			lbinfo.setText("请输入密码！");
		} else {
			if (!psw.equals(psws)) {
				lbinfo.setText("密码不一致！");
			} else {
				boolean flag = admitBuss.updateAdmit(new Admit(id, jtfpsw
						.getText()));
				if (flag) {
					JOptionPane.showMessageDialog(null, "信息修改成功！");
					jtfpsw.setText("");
					jtfpsws.setText("");
				} else {
					lbinfo.setText("信息修改失败！");
				}
			}
		}
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JTextField jtfaid;
	private javax.swing.JPasswordField jtfpsw;
	private javax.swing.JPasswordField jtfpsws;
	private javax.swing.JLabel lbinfo;
	// End of variables declaration//GEN-END:variables

}