/*
 * UserUpdaInfoView.java
 *
 * Created on __DATE__, __TIME__
 */

package win.wangshengan.hotelhousing.view;

import javax.swing.JOptionPane;

import win.wangshengan.hotelhousing.business.UserzBuss;
import win.wangshengan.hotelhousing.business.impl.UserzBussImpl;
import win.wangshengan.hotelhousing.entity.Userz;
import win.wangshengan.hotelhousing.util.Format;

/**
 *
 * @author  __USER__
 */
public class UserUpdaInfoView extends javax.swing.JPanel {

	UserzBuss userzBuss = new UserzBussImpl();
	String id = "";

	/**
	 * 
	 */
	public UserUpdaInfoView() {
		super();
		initComponents();
		jtfid.setEditable(true);
		lbvip.setEditable(true);
		this.setSize(638, 624);
		this.setOpaque(false);
	}

	/** Creates new form UserUpdaInfoView */
	public UserUpdaInfoView(String id) {
		this.id = id;
		initComponents();
		Userz user = userzBuss.getUserzById(id);
		jtfname.setText(user.getUname());
		jtfid.setText(user.getUserid());
		jtfphone.setText(String.valueOf(user.getUphone()));
		jtfpsw.setText(user.getUpsw());
		int vip = user.getUvip();
		if (vip == 0) {
			lbvip.setText("否");
		} else {
			lbvip.setText("是");
		}
		this.setOpaque(false);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jtfname = new javax.swing.JTextField();
		jLabel6 = new javax.swing.JLabel();
		jtfid = new javax.swing.JTextField();
		jtfphone = new javax.swing.JTextField();
		jtfpsw = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		lbvip = new javax.swing.JTextField();

		setForeground(new java.awt.Color(255, 255, 255));

		jLabel1.setFont(new java.awt.Font("华文新魏", 0, 18));
		jLabel1.setForeground(new java.awt.Color(255, 255, 255));
		jLabel1.setText("\u59d3\u540d");

		jLabel2.setFont(new java.awt.Font("华文新魏", 0, 18));
		jLabel2.setForeground(new java.awt.Color(255, 255, 255));
		jLabel2.setText("\u8eab\u4efd\u8bc1\u53f7");

		jLabel3.setFont(new java.awt.Font("华文新魏", 0, 18));
		jLabel3.setForeground(new java.awt.Color(255, 255, 255));
		jLabel3.setText("\u624b\u673a\u53f7");

		jLabel4.setFont(new java.awt.Font("华文新魏", 0, 18));
		jLabel4.setForeground(new java.awt.Color(255, 255, 255));
		jLabel4.setText("\u5bc6\u7801");

		jLabel5.setFont(new java.awt.Font("华文新魏", 0, 18));
		jLabel5.setForeground(new java.awt.Color(255, 255, 255));
		jLabel5.setText("VIP");

		jLabel6.setFont(new java.awt.Font("华文新魏", 1, 36));
		jLabel6.setForeground(new java.awt.Color(255, 255, 255));
		jLabel6.setText("\u4e2a\u4eba\u4fe1\u606f\u4fee\u6539");

		jtfid.setEditable(false);

		jButton1.setFont(new java.awt.Font("华文新魏", 1, 18));
		jButton1.setForeground(new java.awt.Color(0, 0, 204));
		jButton1.setIcon(new javax.swing.ImageIcon(
				"D:\\MyeclipseWork\\hotelhousing1\\images\\提交.png")); // NOI18N
		jButton1.setText("\u63d0  \u4ea4");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		lbvip.setEditable(false);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(172, 172, 172)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.TRAILING)
												.addComponent(
														jLabel6,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														243,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGroup(
														layout.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
																.addGroup(
																		layout.createSequentialGroup()
																				.addGroup(
																						layout.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING)
																								.addComponent(
																										jLabel4)
																								.addComponent(
																										jLabel3)
																								.addComponent(
																										jLabel2)
																								.addComponent(
																										jLabel1)
																								.addComponent(
																										jLabel5))
																				.addGap(42,
																						42,
																						42)
																				.addGroup(
																						layout.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								false)
																								.addComponent(
																										lbvip)
																								.addComponent(
																										jtfpsw)
																								.addComponent(
																										jtfphone)
																								.addComponent(
																										jtfid)
																								.addComponent(
																										jtfname,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										142,
																										javax.swing.GroupLayout.PREFERRED_SIZE)))
																.addComponent(
																		jButton1,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		264,
																		javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addContainerGap(202, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(26, 26, 26)
								.addComponent(jLabel6)
								.addGap(49, 49, 49)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														jtfname,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel1))
								.addGap(31, 31, 31)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.TRAILING)
												.addComponent(
														jtfid,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel2))
								.addGap(27, 27, 27)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														jtfphone,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel3))
								.addGap(35, 35, 35)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														jtfpsw,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel4))
								.addGap(38, 38, 38)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel5)
												.addComponent(
														lbvip,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(59, 59, 59).addComponent(jButton1)
								.addContainerGap(177, Short.MAX_VALUE)));
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		String uname = jtfname.getText();
		String userzid = jtfid.getText();
		String uphone = jtfphone.getText();
		String upsw = jtfpsw.getText();
		if ("".equals(userzid)) {
			JOptionPane.showMessageDialog(null, "请输入客户身份证号！");
			return;
		}
		boolean isTrue = Format.isStringToNumber(uphone);
		if (!isTrue) {
			JOptionPane.showMessageDialog(null, "请输入正确手机号！");
		} else {
			Long usphone = Long.valueOf(uphone);
			Userz userz = userzBuss.getUserzById(userzid);
			if (userz.getUname().equals(uname) && userz.getUphone() == usphone
					&& userz.getUserid().equals(userzid)
					&& userz.getUpsw().equals(upsw)) {
				JOptionPane.showMessageDialog(null, "请修改信息后提交！");
			} else {
				boolean flag = userzBuss.updateUserz(new Userz(uname, userzid,
						usphone, upsw));
				if (flag) {
					JOptionPane.showMessageDialog(null, "修改成功！");
				} else {
					JOptionPane.showMessageDialog(null, "对不起，修改失败！");
				}
			}
		}
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JTextField jtfid;
	private javax.swing.JTextField jtfname;
	private javax.swing.JTextField jtfphone;
	private javax.swing.JTextField jtfpsw;
	private javax.swing.JTextField lbvip;
	// End of variables declaration//GEN-END:variables

}