/*
 * UserOrderView.java
 *
 * Created on __DATE__, __TIME__
 */

package win.wangshengan.hotelhousing.view;

import java.sql.Date;
import java.util.List;
import java.util.Vector;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import win.wangshengan.hotelhousing.business.CountsBuss;
import win.wangshengan.hotelhousing.business.RoomBuss;
import win.wangshengan.hotelhousing.business.RoomCheckInBuss;
import win.wangshengan.hotelhousing.business.UserzBuss;
import win.wangshengan.hotelhousing.business.impl.CountsBussImpl;
import win.wangshengan.hotelhousing.business.impl.RoomBussImpl;
import win.wangshengan.hotelhousing.business.impl.RoomCheckInBussImpl;
import win.wangshengan.hotelhousing.business.impl.UserzBussImpl;
import win.wangshengan.hotelhousing.entity.Counts;
import win.wangshengan.hotelhousing.entity.RoomCheckIn;
import win.wangshengan.hotelhousing.entity.Rooms;
import win.wangshengan.hotelhousing.entity.Userz;
import win.wangshengan.hotelhousing.util.Format;

/**
 *
 * @author  __USER__
 */
public class UserOrderView extends javax.swing.JPanel {

	RoomBuss roomBuss = new RoomBussImpl();
	UserzBuss userzBuss = new UserzBussImpl();
	CountsBuss countsBuss = new CountsBussImpl();
	RoomCheckInBuss roomCheckInBuss = new RoomCheckInBussImpl();
	String id = "";

	public UserOrderView() {

	}

	/** Creates new form UserOrderView */
	public UserOrderView(String id) {
		this.id = id;
		initComponents();
		initiaP1();
		fillTable(false); //初始化时无条件填充表格内信息
		this.setSize(638, 624);
		this.setOpaque(false);
		jPanel1.setOpaque(false);
	}

	/**
	 * 初始化房间查询信息框内的下拉框信息
	 */
	private void initiaP1() {
		List<String> ls = roomBuss.getRoomRtype();
		for (String type : ls) {
			cbtype.addItem(type);
		}
		List<String> lst = roomBuss.getRoomRState();
		for (String state : lst) {
			cbstate.addItem(state);
		}
		List<Integer> li = roomBuss.getRoomRvalue();
		for (int value : li) {
			cbvalue.addItem(value);
		}
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jtfno = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();
		cbtype = new javax.swing.JComboBox();
		jLabel4 = new javax.swing.JLabel();
		cbstate = new javax.swing.JComboBox();
		cbvalue = new javax.swing.JComboBox();
		jLabel7 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		jtfbegin = new javax.swing.JTextField();
		jtfend = new javax.swing.JTextField();
		jLabel9 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jtrooms = new javax.swing.JTable();
		jLabel6 = new javax.swing.JLabel();
		jlvalue = new javax.swing.JLabel();
		jButton2 = new javax.swing.JButton();
		jLabel5 = new javax.swing.JLabel();
		lbalert = new javax.swing.JLabel();

		jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(
				javax.swing.BorderFactory.createLineBorder(new java.awt.Color(
						255, 255, 255)), "\u623f\u95f4\u67e5\u8be2",
				javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
				javax.swing.border.TitledBorder.DEFAULT_POSITION,
				new java.awt.Font("华文新魏", 0, 14), new java.awt.Color(255, 255,
						255)));

		jLabel1.setFont(new java.awt.Font("华文新魏", 0, 14));
		jLabel1.setForeground(new java.awt.Color(255, 255, 255));
		jLabel1.setText("\u623f\u95f4\u7f16\u53f7");

		jLabel2.setFont(new java.awt.Font("华文新魏", 0, 14));
		jLabel2.setForeground(new java.awt.Color(255, 255, 255));
		jLabel2.setText("\u623f\u95f4\u578b\u53f7");

		jLabel3.setFont(new java.awt.Font("华文新魏", 0, 14));
		jLabel3.setForeground(new java.awt.Color(255, 255, 255));
		jLabel3.setText("\u623f\u95f4\u4ef7\u683c");

		jButton1.setFont(new java.awt.Font("华文新魏", 1, 18));
		jButton1.setForeground(new java.awt.Color(51, 51, 255));
		jButton1.setIcon(new javax.swing.ImageIcon(
				"D:\\MyeclipseWork\\hotelhousing1\\images\\查询.png")); // NOI18N
		jButton1.setText("\u67e5 \u8be2");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		cbtype.setModel(new javax.swing.DefaultComboBoxModel(
				new String[] { "请选择" }));

		jLabel4.setFont(new java.awt.Font("华文新魏", 0, 14));
		jLabel4.setForeground(new java.awt.Color(255, 255, 255));
		jLabel4.setText("\u623f\u95f4\u72b6\u6001");

		cbstate.setModel(new javax.swing.DefaultComboBoxModel(
				new String[] { "请选择" }));

		cbvalue.setModel(new javax.swing.DefaultComboBoxModel(
				new String[] { "请选择" }));

		jLabel7.setFont(new java.awt.Font("华文新魏", 0, 14));
		jLabel7.setForeground(new java.awt.Color(255, 255, 255));
		jLabel7.setText("\u5165\u4f4f\u65f6\u95f4");

		jLabel8.setFont(new java.awt.Font("华文新魏", 0, 14));
		jLabel8.setForeground(new java.awt.Color(255, 255, 255));
		jLabel8.setText("\u9000\u623f\u65f6\u95f4");

		jLabel9.setForeground(new java.awt.Color(255, 0, 0));
		jLabel9.setText("\u683c\u5f0f\uff1a2017-07-10");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel1)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jtfno,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				65,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel4)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				cbstate,
																				0,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)))
										.addGap(18, 18, 18)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel2)
														.addComponent(jLabel3))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(
																cbtype,
																0,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(cbvalue,
																0, 65,
																Short.MAX_VALUE))
										.addGap(12, 12, 12)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel8)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jtfend,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				104,
																				Short.MAX_VALUE))
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel7)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jtfbegin,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				104,
																				Short.MAX_VALUE)))
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGap(27,
																				27,
																				27)
																		.addComponent(
																				jButton1,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				106,
																				Short.MAX_VALUE)
																		.addContainerGap())
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jLabel9,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				111,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel1)
														.addComponent(
																jtfno,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel2)
														.addComponent(
																cbtype,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel7)
														.addComponent(
																jtfbegin,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel9))
										.addGap(20, 20, 20)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel4)
														.addComponent(
																cbstate,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel3)
														.addComponent(
																cbvalue,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel8)
														.addComponent(jButton1)
														.addComponent(
																jtfend,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(24, 24, 24)));

		jtrooms.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] {

				}, new String[] { "房间编号", "房间型号", "房间状态", "房间价格", "房间配置" }) {
			boolean[] canEdit = new boolean[] { false, false, false, false,
					false };

			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		});
		jtrooms.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jtroomsMouseClicked(evt);
			}
		});
		jScrollPane1.setViewportView(jtrooms);

		jLabel6.setFont(new java.awt.Font("华文新魏", 1, 18));
		jLabel6.setForeground(new java.awt.Color(255, 255, 255));
		jLabel6.setText("\u4ef7\u683c\uffe5");

		jlvalue.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jlvalue.setForeground(new java.awt.Color(255, 0, 0));

		jButton2.setFont(new java.awt.Font("华文新魏", 1, 18));
		jButton2.setForeground(new java.awt.Color(0, 0, 255));
		jButton2.setIcon(new javax.swing.ImageIcon(
				"D:\\MyeclipseWork\\hotelhousing1\\images\\支付.png")); // NOI18N
		jButton2.setText("\u652f\u4ed8");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jLabel5.setFont(new java.awt.Font("华文新魏", 0, 14));
		jLabel5.setForeground(new java.awt.Color(255, 0, 0));
		jLabel5.setText("\u5168\u90fd\u914d\u6709:\u7a7a\u8c03\u3001\u70ed\u6c34\u3001\u5bbd\u5e26\u3001\u72ec\u7acb\u536b\u6d74");

		lbalert.setFont(new java.awt.Font("华文新魏", 0, 18));
		lbalert.setForeground(new java.awt.Color(255, 0, 0));
		lbalert.setText(" ");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														javax.swing.GroupLayout.Alignment.TRAILING,
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addGap(20,
																										20,
																										20)
																								.addComponent(
																										jLabel5,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										251,
																										javax.swing.GroupLayout.PREFERRED_SIZE)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																										267,
																										Short.MAX_VALUE))
																				.addGroup(
																						layout.createSequentialGroup()
																								.addContainerGap()
																								.addComponent(
																										jLabel6)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
																.addGap(15, 15,
																		15)
																.addComponent(
																		jlvalue,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		73,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(
														layout.createSequentialGroup()
																.addContainerGap()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						jScrollPane1,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						614,
																						Short.MAX_VALUE)
																				.addComponent(
																						jPanel1,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						Short.MAX_VALUE)))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(154,
																		154,
																		154)
																.addComponent(
																		lbalert,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		322,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(
														javax.swing.GroupLayout.Alignment.TRAILING,
														layout.createSequentialGroup()
																.addContainerGap(
																		535,
																		Short.MAX_VALUE)
																.addComponent(
																		jButton2)))
								.addContainerGap()));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addComponent(jPanel1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										131,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jScrollPane1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										350,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.TRAILING)
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		jLabel5)
																.addGap(5, 5, 5)
																.addComponent(
																		jLabel6))
												.addComponent(
														jlvalue,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														32,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGap(9, 9, 9)
																.addComponent(
																		lbalert))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(29, 29,
																		29)
																.addComponent(
																		jButton2)))
								.addContainerGap(28, Short.MAX_VALUE)));
	}// </editor-fold>
	//GEN-END:initComponents

	/**
	 * 点击支付按钮把信息添加到数据库中
	 * @param evt
	 */
	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		lbalert.setText(" ");
		/**
		 * 根据ID查询count结算表内是否已经有该客户信息
		 */
		RoomCheckIn roomCheckIn = roomCheckInBuss.getAllRoomCheckInById(id);
		if (roomCheckIn != null) {
			//因为一个身份证号一次只能预定一间房子
			lbalert.setText("警告：您已经定了房间，不能再订了！");
			return;
		}
		Userz user = userzBuss.getUserzById(id);
		String uname = user.getUname();
		String userid = user.getUserid();
		String begTime = jtfbegin.getText();
		String enTime = jtfend.getText();
		if ("".equals(begTime) || "".equals(enTime)) {
			lbalert.setText("警告：请输入您要住房的日期！");
			return;
		}
		if (!Format.isDateFormat(begTime) || !Format.isDateFormat(enTime)) {
			lbalert.setText("警告：请输入正确的日期格式！");
			return;
		}
		Date beginTime = Date.valueOf(begTime);
		Date endTime = Date.valueOf(enTime);
		java.util.Date date = new java.util.Date();	//当前时间
		java.util.Date begin = new java.util.Date(beginTime.getTime());//查询时入房时间
		//检查填写的入房日期是否已过
		if(date.after(begin)){
			lbalert.setText("警告：已过入住时间，请修改！");
			return;
		}
		//获取表单中被选中的行
		int rowNum = jtrooms.getSelectedRow();
		if (rowNum == -1) {
			lbalert.setText("警告：请输入您要预定的房间！");
			return;
		}
		int i = JOptionPane.showConfirmDialog(null, "   是否预定！", "系统消息",
				JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
		//i=0表示是
		if (i == 0) {
			//获取被选中行的房间编号
			String roomno = jtrooms.getValueAt(rowNum, 0) + "";
			int rno = Integer.parseInt(roomno);
			//获取显示的价格
			int rvalue = Integer.parseInt(jlvalue.getText());
			//把所获信息添加到结算表内Counts
			boolean isCount = countsBuss.addCount(new Counts(uname, userid,
					rvalue, 0, 0));
			boolean flag = roomCheckInBuss.addRoomCheckIn(new RoomCheckIn(rno,
					uname, userid, beginTime, endTime, 1, 0));
			boolean isUpdateState = roomBuss.updateRoom(new Rooms(rno, "", "预",
					"", -1));
			if (flag && isCount && isUpdateState) {
				JOptionPane.showMessageDialog(null, "支付成功！");

			} else {
				lbalert.setText("警告：支付失败！");
			}
		}
	}

	/**
	 * 点击表格获得价格
	 * @param evt
	 */
	private void jtroomsMouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		lbalert.setText(" ");
		int rowNum = jtrooms.getSelectedRow();
		int value = (Integer) jtrooms.getValueAt(rowNum, 3);
		String rstate = jtrooms.getValueAt(rowNum, 2) + "";
		String begTime = jtfbegin.getText();
		String enTime = jtfend.getText();
		if (!"空".equals(rstate)) {
			lbalert.setText("提醒：对不起该房间已经被预定了！");
			return;
		}
		if ("".equals(begTime) || "".equals(enTime)) {
			lbalert.setText("警告：请输入您要住房的日期！");
			return;
		}
		if (!Format.isDateFormat(begTime) || !Format.isDateFormat(enTime)) {
			lbalert.setText("警告：请输入正确的日期格式！");
			return;
		}
		Date beginTime = Date.valueOf(begTime);
		Date endTime = Date.valueOf(enTime);
		Long begin = beginTime.getTime() + 43200000;//中午12点后开始算时间
		Long end = endTime.getTime() + 43200000;
		Long time = end - begin;
		jlvalue.setText(value * time / 86400000 + "");
	}

	/**
	 * 填充table
	 */
	private void fillTable(boolean flag) {
		String rno = jtfno.getText();//数据库中为number类型
		String rtype = cbtype.getSelectedItem() + "";
		String rstate = cbstate.getSelectedItem() + "";
		String rvalue = cbvalue.getSelectedItem() + "";//数据库中为number类型
		int roomno = -1;
		int roomvalue = -1;
		if (flag) {
			if (!"".equals(rno) && !"请选择".equals(rvalue)) {
				roomno = Integer.parseInt(rno);
				roomvalue = Integer.parseInt(rvalue);
			} else if ("".equals(rno) && !"请选择".equals(rvalue)) {
				roomvalue = Integer.parseInt(rvalue);
			} else if (!"".equals(rno) && "请选择".equals(rvalue)) {
				roomno = Integer.parseInt(rno);
			}
		}
		List<Rooms> lr = roomBuss.getAllRoomsByCondition(new Rooms(roomno,
				rtype, rstate, "", roomvalue));
		DefaultTableModel dtm = (DefaultTableModel) jtrooms.getModel();
		dtm.setRowCount(0); //设置行的数目为0
		for (Rooms room : lr) {
			Vector v = new Vector();
			v.add(room.getRno());
			v.add(room.getRtype());
			v.add(room.getRstate());
			v.add(room.getRvalue());
			v.add(room.getRconfigue());
			dtm.addRow(v);
		}
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		lbalert.setText(" ");
		fillTable(true); //点击搜索时根据条件查询
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JComboBox cbstate;
	private javax.swing.JComboBox cbtype;
	private javax.swing.JComboBox cbvalue;
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JLabel jlvalue;
	private javax.swing.JTextField jtfbegin;
	private javax.swing.JTextField jtfend;
	private javax.swing.JTextField jtfno;
	private javax.swing.JTable jtrooms;
	private javax.swing.JLabel lbalert;
	// End of variables declaration//GEN-END:variables

}