/*
 * UserHistoryView.java
 *
 * Created on __DATE__, __TIME__
 */

package win.wangshengan.hotelhousing.view;

import java.sql.Date;
import java.util.List;
import java.util.Vector;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import win.wangshengan.hotelhousing.business.HistoryBuss;
import win.wangshengan.hotelhousing.business.UserzBuss;
import win.wangshengan.hotelhousing.business.impl.HistoryBussImpl;
import win.wangshengan.hotelhousing.business.impl.UserzBussImpl;
import win.wangshengan.hotelhousing.entity.History;
import win.wangshengan.hotelhousing.util.Format;

/**
 *
 * @author  __USER__
 */
public class UserHistoryView extends javax.swing.JPanel {

	UserzBuss userzBuss = new UserzBussImpl();
	HistoryBuss historyBuss = new HistoryBussImpl();
	String id = "";

	public UserHistoryView() {
		initComponents();
		jtfname.setEditable(true);
		jtfuid.setEditable(true);
		info(0); //初始化时填充table中信息
		this.setSize(638, 624);
		this.setOpaque(false);
		jPanel1.setOpaque(false);
	}

	/** Creates new form UserHistoryView */
	public UserHistoryView(String id) {
		this.id = id;
		initComponents();
		fillData();
		info(1); //初始化时填充table中信息
		this.setSize(638, 624);
		this.setOpaque(false);
		jPanel1.setOpaque(false);
	}

	/**
	 * 填充个人历史记录中的姓名和客户身份证号
	 */
	private void fillData() {
		jtfname.setText(userzBuss.getUserzById(id).getUname());
		jtfuid.setText(id);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		tb = new javax.swing.JTable();
		jPanel1 = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		jtfname = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		jtfuid = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		jtfrno = new javax.swing.JTextField();
		jLabel5 = new javax.swing.JLabel();
		jtfbegin = new javax.swing.JTextField();
		jLabel6 = new javax.swing.JLabel();
		jtfend = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		lbalert = new javax.swing.JLabel();

		jLabel1.setFont(new java.awt.Font("华文新魏", 1, 24));
		jLabel1.setForeground(new java.awt.Color(255, 255, 255));
		jLabel1.setText("      \u5386\u53f2\u8bb0\u5f55");

		tb.setModel(new javax.swing.table.DefaultTableModel(new Object[][] {

		}, new String[] { "姓名", "身份证号", "房间编号", "入房日期", "退房日期", "操作时间",
				"该操作管理员" }) {
			boolean[] canEdit = new boolean[] { false, false, false, false,
					false, false, false };

			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		});
		jScrollPane1.setViewportView(tb);

		jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(
				javax.swing.BorderFactory.createLineBorder(new java.awt.Color(
						255, 255, 255)), "\u67e5\u8be2\u8bb0\u5f55",
				javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
				javax.swing.border.TitledBorder.DEFAULT_POSITION,
				new java.awt.Font("华文新魏", 0, 14), new java.awt.Color(255, 255,
						255)));
		jPanel1.setForeground(new java.awt.Color(255, 255, 255));

		jLabel2.setFont(new java.awt.Font("华文新魏", 0, 14));
		jLabel2.setForeground(new java.awt.Color(255, 255, 255));
		jLabel2.setText("  \u59d3  \u540d");

		jtfname.setEditable(false);

		jLabel3.setFont(new java.awt.Font("华文新魏", 0, 14));
		jLabel3.setForeground(new java.awt.Color(255, 255, 255));
		jLabel3.setText("\u8eab\u4efd\u8bc1\u53f7");

		jtfuid.setEditable(false);

		jLabel4.setFont(new java.awt.Font("华文新魏", 0, 14));
		jLabel4.setForeground(new java.awt.Color(255, 255, 255));
		jLabel4.setText("\u623f\u95f4\u7f16\u53f7");

		jtfrno.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jtfrnoActionPerformed(evt);
			}
		});

		jLabel5.setFont(new java.awt.Font("华文新魏", 0, 14));
		jLabel5.setForeground(new java.awt.Color(255, 255, 255));
		jLabel5.setText("\u5165\u623f\u65e5\u671f");

		jLabel6.setFont(new java.awt.Font("华文新魏", 0, 14));
		jLabel6.setForeground(new java.awt.Color(255, 255, 255));
		jLabel6.setText("\u9000\u623f\u65e5\u671f");

		jButton1.setFont(new java.awt.Font("华文新魏", 1, 18));
		jButton1.setForeground(new java.awt.Color(0, 0, 255));
		jButton1.setIcon(new javax.swing.ImageIcon(
				"D:\\MyeclipseWork\\hotelhousing1\\images\\查询.png")); // NOI18N
		jButton1.setText("\u67e5\u8be2");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(
																jLabel2,
																javax.swing.GroupLayout.Alignment.TRAILING,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(
																jLabel5,
																javax.swing.GroupLayout.Alignment.TRAILING,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(jtfname)
														.addComponent(
																jtfbegin,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																86,
																Short.MAX_VALUE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(jLabel6)
														.addComponent(jLabel3))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jtfend,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																94,
																Short.MAX_VALUE)
														.addComponent(
																jtfuid,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																94,
																Short.MAX_VALUE))
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGap(5,
																				5,
																				5)
																		.addComponent(
																				jLabel4)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																		.addComponent(
																				jtfrno,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				85,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addContainerGap(
																				98,
																				Short.MAX_VALUE))
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jButton1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				98,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addContainerGap()))));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel2)
														.addComponent(jLabel4)
														.addComponent(jLabel3)
														.addComponent(
																jtfname,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jtfuid,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jtfrno,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel5)
														.addComponent(jLabel6)
														.addComponent(
																jtfbegin,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jtfend,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jButton1))
										.addContainerGap(31, Short.MAX_VALUE)));

		lbalert.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14));
		lbalert.setForeground(new java.awt.Color(255, 0, 0));
		lbalert.setText(" ");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		lbalert,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		163,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGap(221,
																		221,
																		221))
												.addGroup(
														javax.swing.GroupLayout.Alignment.TRAILING,
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING)
																				.addComponent(
																						jPanel1,
																						javax.swing.GroupLayout.Alignment.LEADING,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						Short.MAX_VALUE)
																				.addComponent(
																						jScrollPane1,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						592,
																						Short.MAX_VALUE))
																.addContainerGap())))
				.addGroup(
						layout.createSequentialGroup()
								.addGap(206, 206, 206)
								.addComponent(jLabel1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										176,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(234, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup()
						.addGap(11, 11, 11)
						.addComponent(jLabel1,
								javax.swing.GroupLayout.PREFERRED_SIZE, 24,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18)
						.addComponent(jPanel1,
								javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18)
						.addComponent(jScrollPane1,
								javax.swing.GroupLayout.PREFERRED_SIZE, 290,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18).addComponent(lbalert)
						.addContainerGap(97, Short.MAX_VALUE)));
	}// </editor-fold>
	//GEN-END:initComponents

	private void jtfrnoActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	/**
	 * 查询历史记录
	 * @param flag
	 */
	private void info(int condition) {
		String userid = jtfuid.getText();
		String uname = jtfname.getText();
		String rno = jtfrno.getText();
		String begin = jtfbegin.getText();
		String end = jtfend.getText();
		int roomno = -1;
		Date beginTime = new Date(1);
		Date endTime = new Date(1);
		if (!Format.isRoomno(rno) && !"".equals(rno)) {
			lbalert.setText("警告：请输入正确的房号！");
			return;
		}
		if (!"".equals(rno)) {
			roomno = Integer.parseInt(rno);
		}
		if ((!Format.isDateFormat(begin) || !Format.isDateFormat(end))
				&& (!"".equals(begin) && !"".equals(end))) {
			lbalert.setText("警告：请输入正确的日期！");
			return;
		}
		if (!"".equals(begin)) {
			beginTime = Date.valueOf(begin);
		} else if (!"".equals(end)) {
			endTime = Date.valueOf(end);
		}
		List<History> lh = null;
		if (condition == 2) { //按条件查询
			lh = historyBuss.getAllHistoryByCondition(new History(roomno,
					uname, id, beginTime, endTime, new Date(1), -1));
		} else if (condition == 0) { //管理员初始化界面
			lh = historyBuss.getAllHistoryByCondition(new History(-1, "", "",
					new Date(1), new Date(1), new Date(1), -1));
		} else if (condition == 1) { //客户初始化界面
			lh = historyBuss.getAllHistoryByCondition(new History(-1, "", id,
					new Date(1), new Date(1), new Date(1), -1));
		}
		DefaultTableModel dtm = (DefaultTableModel) tb.getModel();
		dtm.setRowCount(0);
		for (History h : lh) {
			Vector v = new Vector();
			v.add(h.getUname());
			v.add(h.getUserid());
			v.add(h.getRno());
			v.add(h.getBeginTime());
			v.add(h.getEndTime());
			v.add(h.getOperaDate());
			v.add(h.getAdmin());
			dtm.addRow(v);
		}
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		lbalert.setText("");
		info(2); //按条件查询历史记录
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextField jtfbegin;
	private javax.swing.JTextField jtfend;
	private javax.swing.JTextField jtfname;
	private javax.swing.JTextField jtfrno;
	private javax.swing.JTextField jtfuid;
	private javax.swing.JLabel lbalert;
	private javax.swing.JTable tb;
	// End of variables declaration//GEN-END:variables

}