/*
 * UserView.java
 *
 * Created on __DATE__, __TIME__
 */

package win.wangshengan.hotelhousing.view;

import java.awt.Color;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

import win.wangshengan.hotelhousing.business.UserzBuss;
import win.wangshengan.hotelhousing.business.impl.UserzBussImpl;
import win.wangshengan.hotelhousing.entity.Userz;
import win.wangshengan.hotelhousing.util.ViewUtil;

/**
 *
 * @author  __USER__
 */
public class UserView extends javax.swing.JFrame {

	JFrame frame = null;

	public UserView() {

	}

	/** Creates new form UserView */
	public UserView(JFrame frame) {
		this.frame = frame;
		initComponents();
		ViewUtil.viewLocationCenter(this);
		ViewUtil.addBackground(this, "images/9.jpg", 510, 462);
		jButton1.setBackground(Color.green);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jtfname = new javax.swing.JTextField();
		jtfid = new javax.swing.JTextField();
		jtfphone = new javax.swing.JTextField();
		jtfpsw = new javax.swing.JPasswordField();
		jtfpsws = new javax.swing.JPasswordField();
		jButton1 = new javax.swing.JButton();
		jLabel7 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setFont(new java.awt.Font("华文新魏", 1, 36));
		jLabel1.setForeground(new java.awt.Color(0, 255, 0));
		jLabel1.setText("\u6ce8 \u518c \u8d26 \u53f7");

		jLabel2.setFont(new java.awt.Font("华文新魏", 0, 18));
		jLabel2.setForeground(new java.awt.Color(255, 255, 255));
		jLabel2.setText("      \u59d3  \u540d\uff1a");

		jLabel3.setFont(new java.awt.Font("华文新魏", 0, 18));
		jLabel3.setForeground(new java.awt.Color(255, 255, 255));
		jLabel3.setText(" \u8eab\u4efd\u8bc1\u53f7\uff1a");

		jLabel4.setFont(new java.awt.Font("华文新魏", 0, 18));
		jLabel4.setForeground(new java.awt.Color(255, 255, 255));
		jLabel4.setText("     \u624b\u673a\u53f7\uff1a");

		jLabel5.setFont(new java.awt.Font("华文新魏", 0, 18));
		jLabel5.setForeground(new java.awt.Color(255, 255, 255));
		jLabel5.setText("      \u5bc6  \u7801\uff1a");

		jLabel6.setFont(new java.awt.Font("华文新魏", 0, 18));
		jLabel6.setForeground(new java.awt.Color(255, 255, 255));
		jLabel6.setText("  \u786e\u8ba4\u5bc6\u7801\uff1a");

		jButton1.setFont(new java.awt.Font("华文新魏", 1, 18));
		jButton1.setForeground(new java.awt.Color(255, 255, 255));
		jButton1.setIcon(new javax.swing.ImageIcon(
				"D:\\MyeclipseWork\\hotelhousing1\\images\\注册.png")); // NOI18N
		jButton1.setText("\u7acb\u5373\u6ce8\u518c");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jLabel7.setFont(new java.awt.Font("华文新魏", 0, 18));
		jLabel7.setForeground(new java.awt.Color(255, 255, 255));
		jLabel7.setIcon(new javax.swing.ImageIcon(
				"D:\\MyeclipseWork\\hotelhousing1\\images\\返回.png")); // NOI18N
		jLabel7.setText("\u4e3b\u754c\u9762");
		jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jLabel7MouseClicked(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup().addContainerGap()
								.addComponent(jLabel7).addGap(92, 92, 92)
								.addComponent(jLabel1)
								.addContainerGap(128, Short.MAX_VALUE))
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addGap(89, 89, 89)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						jLabel6,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						107,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addGroup(
																						layout.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								false)
																								.addComponent(
																										jLabel5,
																										javax.swing.GroupLayout.DEFAULT_SIZE,
																										javax.swing.GroupLayout.DEFAULT_SIZE,
																										Short.MAX_VALUE)
																								.addComponent(
																										jLabel2,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										85,
																										javax.swing.GroupLayout.PREFERRED_SIZE))
																				.addComponent(
																						jLabel4,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						107,
																						Short.MAX_VALUE)
																				.addComponent(
																						jLabel3,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						107,
																						Short.MAX_VALUE))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING,
																				false)
																				.addComponent(
																						jtfpsws)
																				.addComponent(
																						jtfpsw)
																				.addComponent(
																						jtfphone)
																				.addComponent(
																						jtfid)
																				.addComponent(
																						jtfname,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						208,
																						javax.swing.GroupLayout.PREFERRED_SIZE)))
												.addGroup(
														javax.swing.GroupLayout.Alignment.TRAILING,
														layout.createSequentialGroup()
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																		36,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(
																		jButton1,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		264,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGap(20, 20,
																		20)))
								.addGap(82, 82, 82)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addContainerGap()
																.addComponent(
																		jLabel7))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(29, 29,
																		29)
																.addComponent(
																		jLabel1)))
								.addGap(38, 38, 38)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														jtfname,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel2))
								.addGap(35, 35, 35)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.TRAILING)
												.addComponent(
														jtfid,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel3))
								.addGap(36, 36, 36)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														jtfphone,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel4))
								.addGap(27, 27, 27)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														jtfpsw,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel5))
								.addGap(33, 33, 33)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel6)
												.addComponent(
														jtfpsws,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(48, 48, 48).addComponent(jButton1)
								.addContainerGap(38, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		this.dispose();
		frame.setVisible(true);
	}

	/**
	 * 电话号码格式化
	 * @param tel
	 * @return
	 */
	private boolean telCheck(String tel) {
		Pattern p = Pattern
				.compile("^((13\\d{9}$)|(15[0,1,2,3,5,6,7,8,9]\\d{8}$)|(18[0,2,5,6,7,8,9]\\d{8}$)|(147\\d{8})$)");
		Matcher m = p.matcher(tel);
		return m.matches();
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		UserzBuss userzBuss = new UserzBussImpl();
		String uname = jtfname.getText();
		String userId = jtfid.getText();
		String uphone = jtfphone.getText();
		String upsw = jtfpsw.getText();
		String upsws = jtfpsws.getText();
		if ("".equals(uname) || "".equals(userId) || "".equals(uphone)
				|| "".equals(upsw)) {
			JOptionPane.showMessageDialog(null, "请填写完整信息！");
		} else if (!telCheck(uphone)) {
			JOptionPane.showMessageDialog(null, "对不起，请输入正确电话号码！");
		} else if (!upsw.equals(upsws)) {
			JOptionPane.showMessageDialog(null, "两个输入密码不同！请重新输入！");
		} else {
			List<Userz> lu = userzBuss.getAllUserz();
			boolean flag = false;
			for (Userz u : lu) {
				if (userId.equals(u.getUserid())) {
					flag = true;
					break;
				}
			}
			if (flag) {
				JOptionPane.showMessageDialog(null, "系统提醒",
						"对不起，您已经注册了，不能再注册了！", JOptionPane.WARNING_MESSAGE);
			} else {
				boolean isAdd = userzBuss.addUserz(new Userz(uname, userId,
						Long.valueOf(uphone), upsw));
				if (isAdd) {
					JOptionPane.showMessageDialog(null, "注册成功！");
					this.dispose();
				} else {
					JOptionPane.showMessageDialog(null, "对不起，注册失败！");
				}
			}
		}
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new UserView().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JTextField jtfid;
	private javax.swing.JTextField jtfname;
	private javax.swing.JTextField jtfphone;
	private javax.swing.JPasswordField jtfpsw;
	private javax.swing.JPasswordField jtfpsws;
	// End of variables declaration//GEN-END:variables

}